CREATE TABLE IF NOT EXISTS room_booking (
    id INT AUTO_INCREMENT PRIMARY KEY,
    room_id int NOT NULL,
    booking_date TIMESTAMP DEFAULT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    status VARCHAR(100) DEFAULT null,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (room_id) REFERENCES room(id)
);